requires-python = ">=3.11"

[tool.ruff]
line-length = 120
exclude = [
    ".eggs",
    ".git",
    ".git-rewrite",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "site-packages",
    "venv",
    "static",
    "media",
]

[tool.ruff.lint]
select = ["B", "E", "F", "I", "W"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = 'skillsup.settings'

# Directories that are not visited by pytest collector:
norecursedirs = [
  '.git',
  '.github',
  '.pytest_cache',
  '.tox',
  '.vscode',
  '.venv',
  'venv',
  '__pycache__',
  'hooks',
  '*.egg',
  '.eggs',
  'dist',
  'build',
  'docs',
]

# Extra options:
addopts = [
  '--strict-markers',
  '--tb=short',
  '--doctest-modules',
]

testpaths = 'tests/'

python_files = 'test_*.py'

filterwarnings = [
#  'error',
  'ignore::ImportWarning:importlib',
#  'ignore::RemovedInDjango50Warning',
  'ignore::DeprecationWarning:django.http.request',
  'ignore::DeprecationWarning:kombu.utils.compat',
  'ignore::DeprecationWarning:telegram',
  'ignore::PendingDeprecationWarning:django',
]

env = [
  'DEBUG=False',
  'SECRET_KEY=test-secret-key',
  'CELERY_BROKER_URL=memory://localhost/',
  'CELERY_RESULT_BACKEND=file:///tmp',
]

[tool.coverage.run]
omit = [
  '*/migrations/*',
  '*/management/*',
]
